services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
        - /var/lib/postgresql/data
  ecomm:
    image: sinarhen/ecomm:latest
    build: 
      context: .
      dockerfile: src/Api/Dockerfile
    environment:
      - AllowedHosts=*
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DB_CONNECTION_STRING=Host=postgres;Port=5432;Database=postgres;Username=postgres;Password=postgres
      - JWT_ISSUER=http://localhost:5000
      - JWT_AUDIENCE=http://localhost:3000
      - JWT_KEY=super-secret-jwt-key-123
      - ADMIN_EMAIL=admin@admin.dev
      - ADMIN_PASSWORD=Pass123$
      - ADMIN_USERNAME=adminDev
    ports:
        - 5000:80
    depends_on:
      - postgres