services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
        - /var/lib/postgresql/data
  ecomm:
    image: sinarhen/ecomm:latest
    build: 
      context: .
      dockerfile: src/Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_URLS=http://+:7777
    ports:
        - 7001:80
    depends_on:
        - postgres